-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admin_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  title text NOT NULL,
  description text NOT NULL DEFAULT ''::text,
  read boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  link text,
  CONSTRAINT admin_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT admin_notifications_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.booking_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  provider_id uuid NOT NULL,
  assignment_type text NOT NULL DEFAULT 'manual'::text CHECK (assignment_type = ANY (ARRAY['manual'::text, 'auto'::text])),
  assigned_by uuid,
  assigned_at timestamp with time zone DEFAULT now(),
  status text DEFAULT 'assigned'::text CHECK (status = ANY (ARRAY['assigned'::text, 'accepted'::text, 'declined'::text, 'reassigned'::text, 'cancelled'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT booking_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT booking_assignments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_assignments_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.service_providers(id)
);
CREATE TABLE public.booking_time_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  provider_id uuid NOT NULL,
  business_id uuid NOT NULL,
  provider_status text NOT NULL DEFAULT 'on_the_way'::text CHECK (provider_status = ANY (ARRAY['on_the_way'::text, 'at_location'::text, 'clocked_in'::text, 'lunch_break'::text, 'completed'::text])),
  on_the_way_at timestamp with time zone,
  at_location_at timestamp with time zone,
  clocked_in_at timestamp with time zone,
  clocked_out_at timestamp with time zone,
  lunch_start_at timestamp with time zone,
  lunch_end_at timestamp with time zone,
  travel_distance_km numeric,
  travel_time_minutes numeric,
  time_reported_minutes numeric,
  admin_status text DEFAULT 'pending'::text CHECK (admin_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  admin_notes text,
  needs_attention boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  occurrence_date date,
  CONSTRAINT booking_time_logs_pkey PRIMARY KEY (id),
  CONSTRAINT booking_time_logs_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_time_logs_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.service_providers(id),
  CONSTRAINT booking_time_logs_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid,
  service_id uuid,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text, 'draft'::text, 'quote'::text, 'expired'::text])),
  draft_quote_expires_on date,
  scheduled_date date,
  scheduled_time time without time zone,
  address text NOT NULL,
  apt_no text,
  zip_code text,
  notes text,
  total_price numeric NOT NULL,
  payment_method text CHECK (payment_method = ANY (ARRAY['cash'::text, 'online'::text])),
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'paid'::text, 'refunded'::text, 'voided'::text, 'declined'::text])),
  tip_amount numeric DEFAULT 0,
  tip_updated_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  amount numeric,
  business_id uuid NOT NULL,
  customer_email text,
  customer_name text,
  customer_phone text,
  service text,
  date date,
  time time without time zone,
  customer_id uuid,
  provider_wage numeric,
  provider_wage_type text CHECK (provider_wage_type = ANY (ARRAY['percentage'::text, 'fixed'::text, 'hourly'::text])),
  frequency text,
  provider_name text,
  customization jsonb,
  duration_minutes integer,
  unassigned_priority text DEFAULT 'medium'::text CHECK (unassigned_priority IS NULL OR (unassigned_priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text]))),
  assignment_source text DEFAULT 'manual'::text CHECK (assignment_source IS NULL OR (assignment_source = ANY (ARRAY['manual'::text, 'auto'::text, 'invitation'::text, 'grab'::text]))),
  cancellation_fee_amount numeric,
  cancellation_fee_currency text,
  exclude_cancellation_fee boolean NOT NULL DEFAULT false,
  exclude_customer_notification boolean NOT NULL DEFAULT false,
  exclude_provider_notification boolean NOT NULL DEFAULT false,
  private_booking_notes jsonb NOT NULL DEFAULT '[]'::jsonb,
  private_customer_notes jsonb NOT NULL DEFAULT '[]'::jsonb,
  service_provider_notes jsonb NOT NULL DEFAULT '[]'::jsonb,
  recurring_series_id uuid,
  completed_occurrence_dates ARRAY DEFAULT '{}'::text[],
  adjust_service_total boolean NOT NULL DEFAULT false,
  adjustment_service_total_amount numeric,
  adjust_price boolean NOT NULL DEFAULT false,
  adjustment_amount numeric,
  adjust_time boolean NOT NULL DEFAULT false,
  price_adjustment_note text,
  time_adjustment_note text,
  coupon_code text,
  coupon_mode text,
  coupon_discount_type text CHECK (coupon_discount_type = ANY (ARRAY['fixed'::text, 'percentage'::text])),
  coupon_discount_value numeric,
  coupon_discount_amount numeric,
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT bookings_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT bookings_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT bookings_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.service_providers(id),
  CONSTRAINT bookings_recurring_series_id_fkey FOREIGN KEY (recurring_series_id) REFERENCES public.recurring_series(id)
);
CREATE TABLE public.business_access_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL UNIQUE,
  customer_blocked_message text DEFAULT 'We apologize for the inconvenience. Please contact our office if you have any questions.'::text,
  provider_deactivated_message text DEFAULT 'We apologize for the inconvenience. Please contact our office if you have any questions.'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT business_access_settings_pkey PRIMARY KEY (id),
  CONSTRAINT business_access_settings_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.business_cancellation_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL UNIQUE,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT business_cancellation_settings_pkey PRIMARY KEY (id),
  CONSTRAINT business_cancellation_settings_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.business_holidays (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  name text NOT NULL,
  holiday_date date NOT NULL,
  recurring boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT business_holidays_pkey PRIMARY KEY (id),
  CONSTRAINT business_holidays_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.business_reserve_slot_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  maximum_by_day jsonb NOT NULL DEFAULT '{}'::jsonb,
  quick_add_spots jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT business_reserve_slot_settings_pkey PRIMARY KEY (id),
  CONSTRAINT business_reserve_slot_settings_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.business_spot_limits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  max_bookings_per_day integer NOT NULL DEFAULT 10,
  max_bookings_per_week integer NOT NULL DEFAULT 50,
  max_bookings_per_month integer NOT NULL DEFAULT 200,
  max_advance_booking_days integer NOT NULL DEFAULT 90,
  enabled boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT business_spot_limits_pkey PRIMARY KEY (id),
  CONSTRAINT business_spot_limits_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.business_store_options (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  scheduling_type text NOT NULL DEFAULT 'accepted_automatically'::text CHECK (scheduling_type = ANY (ARRAY['accepted_automatically'::text, 'accept_or_decline'::text, 'accepts_same_day_only'::text])),
  accept_decline_timeout_minutes integer DEFAULT 60,
  providers_can_see_unassigned boolean DEFAULT true,
  providers_can_see_all_unassigned boolean DEFAULT false,
  notify_providers_on_unassigned boolean DEFAULT true,
  waitlist_enabled boolean DEFAULT false,
  clock_in_out_enabled boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  booking_completion_mode text NOT NULL DEFAULT 'manual'::text CHECK (booking_completion_mode = ANY (ARRAY['manual'::text, 'automatic'::text])),
  spots_based_on_provider_availability boolean DEFAULT true,
  provider_assignment_mode text NOT NULL DEFAULT 'automatic'::text CHECK (provider_assignment_mode = ANY (ARRAY['manual'::text, 'automatic'::text])),
  recurring_update_default text NOT NULL DEFAULT 'all_future'::text CHECK (recurring_update_default = ANY (ARRAY['this_booking_only'::text, 'all_future'::text])),
  specific_provider_for_customers boolean DEFAULT false,
  specific_provider_for_admin boolean DEFAULT true,
  same_provider_for_recurring_cron boolean DEFAULT true,
  max_minutes_per_provider_per_booking integer DEFAULT 0,
  spot_limits_enabled boolean DEFAULT false,
  holiday_skip_to_next boolean DEFAULT false,
  holiday_blocked_who text NOT NULL DEFAULT 'customer'::text CHECK (holiday_blocked_who = ANY (ARRAY['customer'::text, 'both'::text])),
  show_provider_score_to_customers boolean DEFAULT true,
  show_provider_completed_jobs_to_customers boolean DEFAULT true,
  show_provider_availability_to_customers boolean DEFAULT true,
  time_tracking_mode text NOT NULL DEFAULT 'timestamps_only'::text CHECK (time_tracking_mode = ANY (ARRAY['timestamps_only'::text, 'timestamps_and_gps'::text])),
  distance_unit text NOT NULL DEFAULT 'miles'::text CHECK (distance_unit = ANY (ARRAY['miles'::text, 'kilometers'::text])),
  disable_auto_clock_in boolean DEFAULT false,
  auto_clock_out_enabled boolean DEFAULT false,
  auto_clock_out_distance_meters integer DEFAULT 500,
  completion_on_clock_out boolean DEFAULT false,
  allow_reclock_in boolean DEFAULT false,
  time_log_updates_booking boolean DEFAULT false,
  location_management text NOT NULL DEFAULT 'zip'::text CHECK (location_management = ANY (ARRAY['zip'::text, 'name'::text, 'none'::text])),
  wildcard_zip_enabled boolean NOT NULL DEFAULT true,
  show_location_name_at_end boolean NOT NULL DEFAULT false,
  price_adjustment_note_enabled boolean NOT NULL DEFAULT false,
  time_adjustment_note_enabled boolean NOT NULL DEFAULT false,
  allow_customer_self_reschedule boolean NOT NULL DEFAULT false,
  reschedule_message text,
  CONSTRAINT business_store_options_pkey PRIMARY KEY (id),
  CONSTRAINT business_store_options_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.business_website_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL UNIQUE,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT business_website_configs_pkey PRIMARY KEY (id),
  CONSTRAINT business_website_configs_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.businesses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  address text,
  category character varying,
  plan character varying DEFAULT 'starter'::character varying,
  owner_id uuid,
  subdomain character varying UNIQUE,
  domain character varying UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean DEFAULT true,
  business_email character varying,
  business_phone character varying,
  city character varying,
  zip_code character varying,
  website character varying,
  description text,
  business_image text,
  logo_url text,
  stripe_connect_account_id text,
  CONSTRAINT businesses_pkey PRIMARY KEY (id),
  CONSTRAINT businesses_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL,
  name character varying NOT NULL,
  phone character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  business_id uuid NOT NULL,
  address text,
  join_date timestamp with time zone DEFAULT now(),
  total_bookings integer DEFAULT 0,
  total_spent numeric DEFAULT 0.00,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  last_booking timestamp with time zone,
  auth_user_id uuid,
  avatar text,
  email_notifications boolean DEFAULT true,
  sms_notifications boolean DEFAULT true,
  push_notifications boolean DEFAULT true,
  tags ARRAY DEFAULT '{}'::text[],
  access_blocked boolean DEFAULT false,
  booking_blocked boolean DEFAULT false,
  company text,
  first_name character varying,
  last_name character varying,
  gender character varying DEFAULT 'unspecified'::character varying,
  notes text,
  sms_reminders boolean DEFAULT true,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT customers_auth_user_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.drive_files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  file_type text NOT NULL CHECK (file_type = ANY (ARRAY['document'::text, 'image'::text, 'video'::text, 'other'::text])),
  mime_type text NOT NULL,
  size_bytes integer NOT NULL,
  storage_url text NOT NULL,
  bucket_name text NOT NULL DEFAULT 'drive-files'::text,
  storage_path text NOT NULL,
  owner_type text NOT NULL CHECK (owner_type = ANY (ARRAY['customer'::text, 'provider'::text])),
  owner_id uuid NOT NULL,
  parent_id uuid,
  is_folder boolean DEFAULT false,
  folder_path text DEFAULT ''::text,
  uploaded_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT drive_files_pkey PRIMARY KEY (id),
  CONSTRAINT drive_files_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.drive_files(id),
  CONSTRAINT drive_files_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.drive_folders (
  id uuid NOT NULL,
  description text,
  color text DEFAULT '#3B82F6'::text,
  is_system_folder boolean DEFAULT false,
  CONSTRAINT drive_folders_pkey PRIMARY KEY (id),
  CONSTRAINT drive_folders_id_fkey FOREIGN KEY (id) REFERENCES public.drive_files(id)
);
CREATE TABLE public.email_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  subject text NOT NULL,
  body text NOT NULL,
  template text NOT NULL CHECK (template = ANY (ARRAY['holiday'::text, 'coupon'::text, 'advertisement'::text, 'custom'::text])),
  recipients ARRAY NOT NULL DEFAULT '{}'::text[],
  sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT email_campaigns_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.general_tags (
  business_id uuid NOT NULL,
  name text NOT NULL,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id text NOT NULL DEFAULT generate_general_tag_id(),
  CONSTRAINT general_tags_pkey PRIMARY KEY (id),
  CONSTRAINT general_tags_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.gift_card_instances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  gift_card_id uuid NOT NULL,
  unique_code text NOT NULL UNIQUE,
  original_amount numeric NOT NULL,
  current_balance numeric NOT NULL,
  purchaser_id uuid,
  recipient_id uuid,
  purchaser_email text,
  recipient_email text,
  purchase_date timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'expired'::text, 'fully_redeemed'::text, 'cancelled'::text])),
  message text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gift_card_instances_pkey PRIMARY KEY (id),
  CONSTRAINT gift_card_instances_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT gift_card_instances_gift_card_id_fkey FOREIGN KEY (gift_card_id) REFERENCES public.marketing_gift_cards(id)
);
CREATE TABLE public.gift_card_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  gift_card_instance_id uuid NOT NULL,
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['purchase'::text, 'redemption'::text, 'refund'::text, 'adjustment'::text])),
  amount numeric NOT NULL,
  balance_before numeric NOT NULL,
  balance_after numeric NOT NULL,
  booking_id uuid,
  customer_id uuid,
  description text,
  processed_by uuid,
  transaction_date timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gift_card_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT gift_card_transactions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT gift_card_transactions_gift_card_instance_id_fkey FOREIGN KEY (gift_card_instance_id) REFERENCES public.gift_card_instances(id)
);
CREATE TABLE public.industries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  business_id uuid NOT NULL,
  is_custom boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT industries_pkey PRIMARY KEY (id),
  CONSTRAINT industries_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.industry_exclude_parameter (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  industry_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  price numeric DEFAULT 0,
  time_minutes integer DEFAULT 0,
  display text DEFAULT 'Customer Frontend, Backend & Admin'::text CHECK (display = ANY (ARRAY['Customer Frontend, Backend & Admin'::text, 'Customer Backend & Admin'::text, 'Admin Only'::text])),
  service_category text,
  frequency text,
  show_based_on_frequency boolean DEFAULT false,
  show_based_on_service_category boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  icon text,
  excluded_providers ARRAY DEFAULT '{}'::text[],
  show_based_on_variables boolean DEFAULT false,
  variables jsonb DEFAULT '{}'::jsonb,
  qty_based boolean NOT NULL DEFAULT false,
  maximum_quantity integer,
  apply_to_all_bookings boolean NOT NULL DEFAULT true,
  CONSTRAINT industry_exclude_parameter_pkey PRIMARY KEY (id),
  CONSTRAINT industry_exclude_parameter_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT industry_exclude_parameter_industry_id_fkey FOREIGN KEY (industry_id) REFERENCES public.industries(id)
);
CREATE TABLE public.industry_extras (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  time_minutes integer NOT NULL,
  service_category text,
  price numeric NOT NULL,
  display text NOT NULL DEFAULT 'frontend-backend-admin'::text,
  qty_based boolean DEFAULT false,
  exempt_from_discount boolean DEFAULT false,
  description text,
  show_based_on_frequency boolean DEFAULT false,
  frequency_options ARRAY,
  show_based_on_service_category boolean DEFAULT false,
  service_category_options ARRAY,
  show_based_on_variables boolean DEFAULT false,
  variable_options ARRAY,
  industry_id uuid NOT NULL,
  business_id uuid NOT NULL,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  excluded_providers ARRAY DEFAULT '{}'::text[],
  maximum_quantity integer,
  icon text,
  CONSTRAINT industry_extras_pkey PRIMARY KEY (id),
  CONSTRAINT industry_extras_industry_id_fkey FOREIGN KEY (industry_id) REFERENCES public.industries(id),
  CONSTRAINT industry_extras_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.industry_frequency (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  industry_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  different_on_customer_end boolean DEFAULT false,
  show_explanation boolean DEFAULT false,
  enable_popup boolean DEFAULT false,
  display text NOT NULL DEFAULT 'Both'::text CHECK (display = ANY (ARRAY['Both'::text, 'Booking'::text, 'Quote'::text])),
  occurrence_time text NOT NULL CHECK (occurrence_time = ANY (ARRAY['onetime'::text, 'recurring'::text])),
  discount numeric NOT NULL DEFAULT 0,
  discount_type text NOT NULL DEFAULT '%'::text CHECK (discount_type = ANY (ARRAY['%'::text, '$'::text])),
  is_default boolean DEFAULT false,
  excluded_providers ARRAY DEFAULT '{}'::text[],
  add_to_other_industries boolean DEFAULT false,
  enabled_industries ARRAY DEFAULT '{}'::text[],
  show_based_on_location boolean DEFAULT false,
  location_ids ARRAY DEFAULT '{}'::text[],
  service_categories ARRAY DEFAULT '{}'::text[],
  bathroom_variables ARRAY DEFAULT '{}'::text[],
  sqft_variables ARRAY DEFAULT '{}'::text[],
  bedroom_variables ARRAY DEFAULT '{}'::text[],
  exclude_parameters ARRAY DEFAULT '{}'::text[],
  extras ARRAY DEFAULT '{}'::text[],
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  frequency_repeats text,
  shorter_job_length text,
  shorter_job_length_by text,
  exclude_first_appointment boolean DEFAULT false,
  frequency_discount text,
  charge_one_time_price boolean DEFAULT false,
  CONSTRAINT industry_frequency_pkey PRIMARY KEY (id),
  CONSTRAINT industry_frequency_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT industry_frequency_industry_id_fkey FOREIGN KEY (industry_id) REFERENCES public.industries(id)
);
CREATE TABLE public.industry_location (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  location_id uuid NOT NULL,
  industry_id uuid NOT NULL,
  business_id uuid NOT NULL,
  add_to_other_industries boolean DEFAULT false,
  enabled_industry_ids ARRAY DEFAULT '{}'::text[],
  frequency_ids ARRAY DEFAULT '{}'::text[],
  service_category_ids ARRAY DEFAULT '{}'::text[],
  variable_ids ARRAY DEFAULT '{}'::text[],
  exclude_param_ids ARRAY DEFAULT '{}'::text[],
  extra_ids ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT industry_location_pkey PRIMARY KEY (id),
  CONSTRAINT industry_location_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT industry_location_industry_id_fkey FOREIGN KEY (industry_id) REFERENCES public.industries(id),
  CONSTRAINT industry_location_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.industry_pricing_parameter (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  industry_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  variable_category text NOT NULL,
  price numeric DEFAULT 0,
  time_minutes integer DEFAULT 0,
  display text DEFAULT 'Customer Frontend, Backend & Admin'::text CHECK (display = ANY (ARRAY['Customer Frontend, Backend & Admin'::text, 'Customer Backend & Admin'::text, 'Admin Only'::text])),
  service_category text,
  service_category2 text,
  frequency text,
  is_default boolean DEFAULT false,
  show_based_on_frequency boolean DEFAULT false,
  show_based_on_service_category boolean DEFAULT false,
  show_based_on_service_category2 boolean DEFAULT false,
  excluded_extras ARRAY,
  excluded_services ARRAY,
  excluded_providers ARRAY,
  exclude_parameters ARRAY,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT industry_pricing_parameter_pkey PRIMARY KEY (id),
  CONSTRAINT industry_pricing_parameter_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT industry_pricing_parameter_industry_id_fkey FOREIGN KEY (industry_id) REFERENCES public.industries(id)
);
CREATE TABLE public.industry_service_category (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  color text,
  icon text,
  display text DEFAULT 'customer_frontend_backend_admin'::text CHECK (display = ANY (ARRAY['customer_frontend_backend_admin'::text, 'customer_backend_admin'::text, 'admin_only'::text])),
  display_service_length_customer text DEFAULT 'admin_only'::text CHECK (display_service_length_customer = ANY (ARRAY['customer_frontend_backend_admin'::text, 'customer_backend_admin'::text, 'admin_only'::text])),
  display_service_length_provider boolean DEFAULT false,
  can_customer_edit_service boolean DEFAULT false,
  service_fee_enabled boolean DEFAULT false,
  service_category_frequency boolean DEFAULT false,
  selected_frequencies ARRAY,
  variables jsonb DEFAULT '{}'::jsonb,
  exclude_parameters jsonb DEFAULT '{"pets": false, "smoking": false, "deepCleaning": false}'::jsonb,
  selected_exclude_parameters ARRAY,
  extras ARRAY,
  extras_config jsonb DEFAULT '{"tip": {"saveTo": "all", "display": "customer_frontend_backend_admin", "enabled": false}, "parking": {"saveTo": "all", "display": "customer_frontend_backend_admin", "enabled": false}}'::jsonb,
  expedited_charge jsonb DEFAULT '{"amount": "", "enabled": false, "currency": "$", "displayText": ""}'::jsonb,
  cancellation_fee jsonb DEFAULT '{"fee": "", "type": "single", "enabled": false, "currency": "$", "hoursBefore": "", "payProvider": false, "providerFee": "", "chargeTiming": "beforeDay", "beforeDayTime": "", "providerCurrency": "$"}'::jsonb,
  hourly_service jsonb DEFAULT '{"price": "", "enabled": false, "currency": "$", "priceCalculationType": "customTime", "countExtrasSeparately": false}'::jsonb,
  service_category_price jsonb DEFAULT '{"price": "", "enabled": false, "currency": "$"}'::jsonb,
  service_category_time jsonb DEFAULT '{"hours": "0", "enabled": false, "minutes": "0"}'::jsonb,
  minimum_price jsonb DEFAULT '{"price": "", "enabled": false, "noticeText": "", "textToDisplay": false, "checkAmountType": "discounted", "checkRecurringSchedule": false}'::jsonb,
  override_provider_pay jsonb DEFAULT '{"amount": "", "enabled": false, "currency": "$"}'::jsonb,
  excluded_providers ARRAY,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  industry_id uuid NOT NULL,
  show_explanation_icon_on_form boolean NOT NULL DEFAULT false,
  explanation_tooltip_text text,
  enable_popup_on_selection boolean NOT NULL DEFAULT false,
  popup_content text,
  enable_service_length_tooltip_customer boolean NOT NULL DEFAULT false,
  service_length_tooltip_text_customer text,
  enable_service_length_tooltip_provider boolean NOT NULL DEFAULT false,
  service_length_tooltip_text_provider text,
  CONSTRAINT industry_service_category_pkey PRIMARY KEY (id),
  CONSTRAINT industry_service_category_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT industry_service_category_industry_id_fkey FOREIGN KEY (industry_id) REFERENCES public.industries(id)
);
CREATE TABLE public.invoice_bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL,
  booking_id uuid NOT NULL,
  amount numeric NOT NULL DEFAULT 0,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT invoice_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_bookings_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT invoice_bookings_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.invoice_line_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL,
  description text NOT NULL,
  quantity numeric NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL DEFAULT 0,
  amount numeric NOT NULL,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT invoice_line_items_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_line_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  invoice_number text NOT NULL,
  invoice_type text NOT NULL DEFAULT 'custom'::text CHECK (invoice_type = ANY (ARRAY['custom'::text, 'booking'::text])),
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'paid'::text, 'cancelled'::text])),
  payment_status text NOT NULL DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'partial'::text, 'paid'::text, 'refunded'::text])),
  issue_date date NOT NULL,
  due_date date,
  total_amount numeric NOT NULL DEFAULT 0,
  amount_paid numeric NOT NULL DEFAULT 0,
  currency text DEFAULT 'USD'::text,
  description text,
  notes text,
  billing_address text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  share_token text UNIQUE,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT invoices_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  phone text,
  email text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  tags ARRAY DEFAULT '{}'::text[],
  status text DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'contacted'::text, 'qualified'::text, 'converted'::text, 'lost'::text, 'archived'::text])),
  business_id uuid NOT NULL,
  assigned_staff_id uuid,
  industry_id uuid,
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT leads_assigned_staff_id_fkey FOREIGN KEY (assigned_staff_id) REFERENCES public.staff(id),
  CONSTRAINT leads_industry_id_fkey FOREIGN KEY (industry_id) REFERENCES public.industries(id)
);
CREATE TABLE public.location_search_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  business_id uuid NOT NULL,
  search_query text NOT NULL,
  search_type character varying NOT NULL,
  results_count integer DEFAULT 0,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT location_search_history_pkey PRIMARY KEY (id),
  CONSTRAINT location_search_history_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.location_zip_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  location_id uuid NOT NULL,
  zip_code character varying NOT NULL,
  country character varying DEFAULT 'USA'::character varying,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT location_zip_codes_pkey PRIMARY KEY (id),
  CONSTRAINT location_zip_codes_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.locations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  business_id uuid NOT NULL,
  name character varying NOT NULL,
  address text,
  city character varying,
  state character varying,
  postal_code character varying,
  country character varying DEFAULT 'USA'::character varying,
  latitude numeric CHECK (latitude IS NULL OR latitude >= '-90'::integer::numeric AND latitude <= 90::numeric),
  longitude numeric CHECK (longitude IS NULL OR longitude >= '-180'::integer::numeric AND longitude <= 180::numeric),
  location_type character varying DEFAULT 'service_area'::character varying,
  active boolean DEFAULT true CHECK (active IS NOT NULL),
  osm_place_id character varying,
  osm_type character varying,
  osm_class character varying,
  osm_display_name text,
  service_radius_km numeric CHECK (service_radius_km IS NULL OR service_radius_km > 0::numeric),
  service_area_polygon text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  drawn_shape_json jsonb,
  excluded_provider_ids ARRAY DEFAULT '{}'::text[],
  CONSTRAINT locations_pkey PRIMARY KEY (id),
  CONSTRAINT locations_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT locations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.marketing_coupons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  code text NOT NULL,
  description text,
  discount_type text NOT NULL CHECK (discount_type = ANY (ARRAY['percentage'::text, 'fixed'::text])),
  discount_value numeric NOT NULL,
  start_date date,
  end_date date,
  usage_limit integer,
  min_order numeric,
  active boolean DEFAULT true,
  facebook_coupon boolean DEFAULT false,
  allow_gift_cards boolean DEFAULT false,
  allow_referrals boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  name text,
  CONSTRAINT marketing_coupons_pkey PRIMARY KEY (id),
  CONSTRAINT marketing_coupons_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.marketing_daily_discounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  discount_type text NOT NULL CHECK (discount_type = ANY (ARRAY['percentage'::text, 'fixed'::text])),
  discount_value numeric NOT NULL,
  start_date date,
  end_date date,
  start_time time without time zone,
  end_time time without time zone,
  days ARRAY NOT NULL,
  applies_to text,
  services text,
  categories text,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT marketing_daily_discounts_pkey PRIMARY KEY (id),
  CONSTRAINT marketing_daily_discounts_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.marketing_gift_cards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  code text NOT NULL,
  amount numeric NOT NULL,
  active boolean DEFAULT true,
  expires_in_months integer DEFAULT 12,
  auto_generate_codes boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT marketing_gift_cards_pkey PRIMARY KEY (id),
  CONSTRAINT marketing_gift_cards_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.marketing_scripts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  title text NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['Cold Calling'::text, 'Follow-up'::text, 'SMS'::text])),
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT marketing_scripts_pkey PRIMARY KEY (id),
  CONSTRAINT marketing_scripts_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text,
  phone text,
  role text DEFAULT 'provider'::text CHECK (role = ANY (ARRAY['customer'::text, 'provider'::text, 'admin'::text, 'owner'::text, 'manager'::text, 'staff'::text])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  business_id uuid,
  profile_picture text,
  bio text CHECK (length(bio) <= 500),
  location text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.provider_availability (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_available boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  business_id uuid,
  effective_date date DEFAULT CURRENT_DATE,
  expiry_date date,
  CONSTRAINT provider_availability_pkey PRIMARY KEY (id),
  CONSTRAINT provider_availability_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.service_providers(id),
  CONSTRAINT provider_availability_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.provider_booking_invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  provider_id uuid NOT NULL,
  business_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text])),
  sent_at timestamp with time zone DEFAULT now(),
  responded_at timestamp with time zone,
  response_notes text,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT provider_booking_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT provider_booking_invitations_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT provider_booking_invitations_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.service_providers(id),
  CONSTRAINT provider_booking_invitations_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.provider_capacity (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  max_concurrent_bookings integer DEFAULT 1,
  max_daily_bookings integer DEFAULT 8,
  max_weekly_bookings integer DEFAULT 40,
  current_workload numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT provider_capacity_pkey PRIMARY KEY (id),
  CONSTRAINT provider_capacity_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.service_providers(id)
);
CREATE TABLE public.provider_drive_files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  business_id uuid NOT NULL,
  name text NOT NULL CHECK (char_length(name) > 0),
  type text NOT NULL CHECK (type = ANY (ARRAY['folder'::text, 'file'::text])),
  file_type text CHECK (file_type = ANY (ARRAY['document'::text, 'image'::text, 'video'::text, 'other'::text])),
  size_bytes bigint,
  storage_path text,
  storage_url text,
  parent_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT provider_drive_files_pkey PRIMARY KEY (id),
  CONSTRAINT provider_drive_files_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.service_providers(id),
  CONSTRAINT provider_drive_files_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT provider_drive_files_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.provider_drive_files(id)
);
CREATE TABLE public.provider_earnings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  booking_id uuid NOT NULL,
  service_id uuid,
  gross_amount numeric NOT NULL,
  commission_rate numeric,
  commission_amount numeric NOT NULL,
  net_amount numeric NOT NULL,
  pay_rate_type text NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'paid'::text, 'disputed'::text])),
  payout_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT provider_earnings_pkey PRIMARY KEY (id),
  CONSTRAINT provider_earnings_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT provider_earnings_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.service_providers(id),
  CONSTRAINT provider_earnings_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.provider_invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  email character varying NOT NULL,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  phone character varying,
  address text,
  provider_type character varying DEFAULT 'individual'::character varying CHECK (provider_type::text = ANY (ARRAY['individual'::character varying::text, 'team'::character varying::text])),
  invitation_token character varying NOT NULL UNIQUE,
  temp_password character varying,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'accepted'::character varying::text, 'expired'::character varying::text, 'cancelled'::character varying::text])),
  invited_by uuid,
  invited_at timestamp with time zone DEFAULT now(),
  accepted_at timestamp with time zone,
  expires_at timestamp with time zone DEFAULT (now() + '7 days'::interval),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT provider_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT provider_invitations_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT provider_invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id)
);
CREATE TABLE public.provider_pay_rates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  service_id uuid,
  rate_type text NOT NULL DEFAULT 'flat'::text CHECK (rate_type = ANY (ARRAY['flat'::text, 'percentage'::text, 'hourly'::text])),
  flat_rate numeric,
  percentage_rate numeric CHECK (percentage_rate >= 0::numeric AND percentage_rate <= 100::numeric),
  hourly_rate numeric,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT provider_pay_rates_pkey PRIMARY KEY (id),
  CONSTRAINT provider_pay_rates_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.service_providers(id),
  CONSTRAINT provider_pay_rates_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.provider_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  auto_assignments boolean DEFAULT true,
  email_notifications boolean DEFAULT true,
  sms_notifications boolean DEFAULT false,
  advance_booking_days integer DEFAULT 7,
  minimum_booking_notice_hours integer DEFAULT 2,
  accepts_emergency_bookings boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  working_hours jsonb DEFAULT '{"friday": {"enabled": false, "endTime": "17:00", "startTime": "09:00"}, "monday": {"enabled": false, "endTime": "17:00", "startTime": "09:00"}, "sunday": {"enabled": false, "endTime": "17:00", "startTime": "09:00"}, "tuesday": {"enabled": false, "endTime": "17:00", "startTime": "09:00"}, "saturday": {"enabled": false, "endTime": "17:00", "startTime": "09:00"}, "thursday": {"enabled": false, "endTime": "17:00", "startTime": "09:00"}, "wednesday": {"enabled": false, "endTime": "17:00", "startTime": "09:00"}}'::jsonb,
  CONSTRAINT provider_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT provider_preferences_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.service_providers(id)
);
CREATE TABLE public.provider_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  booking_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  review_text text,
  is_public boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT provider_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT provider_reviews_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.service_providers(id),
  CONSTRAINT provider_reviews_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT provider_reviews_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.provider_service_areas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  area_name text NOT NULL,
  address text NOT NULL,
  city text NOT NULL,
  state text,
  postal_code text,
  latitude numeric,
  longitude numeric,
  radius_km numeric DEFAULT 10,
  is_primary_area boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT provider_service_areas_pkey PRIMARY KEY (id),
  CONSTRAINT provider_service_areas_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.service_providers(id)
);
CREATE TABLE public.provider_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  provider_id uuid NOT NULL,
  service_id uuid NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  skill_level text DEFAULT 'basic'::text CHECK (skill_level = ANY (ARRAY['basic'::text, 'intermediate'::text, 'advanced'::text, 'expert'::text])),
  is_primary_service boolean DEFAULT false,
  years_experience integer DEFAULT 0,
  CONSTRAINT provider_services_pkey PRIMARY KEY (id),
  CONSTRAINT provider_services_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT provider_services_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT provider_services_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.service_providers(id)
);
CREATE TABLE public.recurring_series (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  customer_id uuid,
  customer_name text,
  customer_email text,
  customer_phone text,
  service text,
  address text,
  apt_no text,
  zip_code text,
  notes text,
  total_price numeric DEFAULT 0,
  frequency text NOT NULL,
  frequency_repeats text,
  scheduled_time text,
  duration_minutes integer,
  customization jsonb,
  provider_id uuid,
  provider_name text,
  provider_wage numeric,
  provider_wage_type text,
  payment_method text DEFAULT 'cash'::text,
  start_date date NOT NULL,
  end_date date,
  occurrences_ahead integer NOT NULL DEFAULT 8,
  same_provider boolean DEFAULT true,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'cancelled'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT recurring_series_pkey PRIMARY KEY (id),
  CONSTRAINT recurring_series_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT recurring_series_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT recurring_series_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.service_providers(id)
);
CREATE TABLE public.service_providers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  business_id uuid NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL,
  phone text,
  address text,
  specialization text DEFAULT 'General Services'::text,
  rating numeric DEFAULT 0.0,
  completed_jobs integer DEFAULT 0,
  status text DEFAULT 'active'::text,
  provider_type text DEFAULT 'individual'::text,
  send_email_notification boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  hourly_rate numeric DEFAULT 0,
  payout_method text DEFAULT 'bank_transfer'::text CHECK (payout_method = ANY (ARRAY['bank_transfer'::text, 'stripe'::text, 'paypal'::text, 'cash'::text])),
  total_earned numeric DEFAULT 0,
  total_paid_out numeric DEFAULT 0,
  current_balance numeric DEFAULT 0,
  availability_status text DEFAULT 'available'::text CHECK (availability_status = ANY (ARRAY['available'::text, 'busy'::text, 'unavailable'::text, 'on_vacation'::text])),
  profile_image_url text,
  stripe_account_id text,
  stripe_account_email text,
  stripe_is_connected boolean DEFAULT false,
  stripe_connect_enabled boolean DEFAULT false,
  tags ARRAY DEFAULT '{}'::text[],
  access_blocked boolean DEFAULT false,
  admin_settings jsonb DEFAULT '{}'::jsonb,
  invitation_priority integer DEFAULT 0,
  performance_score numeric DEFAULT 0,
  CONSTRAINT service_providers_pkey PRIMARY KEY (id),
  CONSTRAINT service_providers_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  base_price numeric NOT NULL,
  duration_hours integer NOT NULL,
  service_type text NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  business_id uuid,
  CONSTRAINT services_pkey PRIMARY KEY (id),
  CONSTRAINT services_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);
CREATE TABLE public.staff (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  business_id uuid NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL,
  role text NOT NULL DEFAULT 'staff'::text,
  gender text,
  phone text,
  alternate_phone text,
  address text,
  apartment text,
  send_invitation boolean NOT NULL DEFAULT true,
  image text,
  status text NOT NULL DEFAULT 'active'::text,
  last_active timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT staff_pkey PRIMARY KEY (id),
  CONSTRAINT staff_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.user_activity (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  last_active timestamp with time zone DEFAULT now(),
  business_id uuid,
  CONSTRAINT user_activity_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_activity_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_activity_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email character varying NOT NULL UNIQUE,
  first_name character varying,
  last_name character varying,
  phone character varying,
  role character varying DEFAULT 'customer'::character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);