-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid,
  service_id uuid,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])),
  scheduled_date date,
  scheduled_time time without time zone,
  address text NOT NULL,
  apt_no text,
  zip_code text,
  notes text,
  total_price numeric NOT NULL,
  payment_method text CHECK (payment_method = ANY (ARRAY['cash'::text, 'online'::text])),
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'paid'::text, 'refunded'::text])),
  tip_amount numeric DEFAULT 0,
  tip_updated_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  amount numeric,
  business_id uuid NOT NULL,
  customer_email text,
  customer_name text,
  customer_phone text,
  service text,
  date date,
  time time without time zone,
  customer_id uuid,
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT bookings_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT bookings_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.businesses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  address text,
  category character varying,
  plan character varying DEFAULT 'starter'::character varying,
  owner_id uuid,
  subdomain character varying UNIQUE,
  domain character varying UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean DEFAULT true,
  CONSTRAINT businesses_pkey PRIMARY KEY (id),
  CONSTRAINT businesses_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  phone character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  business_id uuid NOT NULL,
  address text,
  join_date timestamp with time zone DEFAULT now(),
  total_bookings integer DEFAULT 0,
  total_spent numeric DEFAULT 0.00,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  last_booking timestamp with time zone,
  auth_user_id uuid,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT customers_auth_user_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.gift_card_instances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  gift_card_id uuid NOT NULL,
  unique_code text NOT NULL UNIQUE,
  original_amount numeric NOT NULL,
  current_balance numeric NOT NULL,
  purchaser_id uuid,
  recipient_id uuid,
  purchaser_email text,
  recipient_email text,
  purchase_date timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'expired'::text, 'fully_redeemed'::text, 'cancelled'::text])),
  message text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gift_card_instances_pkey PRIMARY KEY (id),
  CONSTRAINT gift_card_instances_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT gift_card_instances_gift_card_id_fkey FOREIGN KEY (gift_card_id) REFERENCES public.marketing_gift_cards(id)
);
CREATE TABLE public.gift_card_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  gift_card_instance_id uuid NOT NULL,
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['purchase'::text, 'redemption'::text, 'refund'::text, 'adjustment'::text])),
  amount numeric NOT NULL,
  balance_before numeric NOT NULL,
  balance_after numeric NOT NULL,
  booking_id uuid,
  customer_id uuid,
  description text,
  processed_by uuid,
  transaction_date timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gift_card_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT gift_card_transactions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT gift_card_transactions_gift_card_instance_id_fkey FOREIGN KEY (gift_card_instance_id) REFERENCES public.gift_card_instances(id)
);
CREATE TABLE public.industries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  business_id uuid NOT NULL,
  is_custom boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT industries_pkey PRIMARY KEY (id),
  CONSTRAINT industries_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.industry_extra (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  industry_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  time_minutes integer NOT NULL DEFAULT 0,
  service_category text,
  price numeric NOT NULL DEFAULT 0,
  display text NOT NULL DEFAULT 'frontend-backend-admin'::text CHECK (display = ANY (ARRAY['frontend-backend-admin'::text, 'backend-admin'::text, 'admin-only'::text])),
  qty_based boolean NOT NULL DEFAULT false,
  exempt_from_discount boolean NOT NULL DEFAULT false,
  service_checklists ARRAY,
  excluded_providers ARRAY,
  show_based_on_frequency boolean NOT NULL DEFAULT false,
  frequency_options ARRAY,
  show_based_on_service_category boolean NOT NULL DEFAULT false,
  service_category_options ARRAY,
  show_based_on_variables boolean NOT NULL DEFAULT false,
  variable_options ARRAY,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT industry_extra_pkey PRIMARY KEY (id),
  CONSTRAINT industry_extra_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  phone text,
  email text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  tags ARRAY DEFAULT '{}'::text[],
  status text DEFAULT 'new'::text,
  business_id uuid NOT NULL,
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.location_search_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  business_id uuid NOT NULL,
  search_query text NOT NULL,
  search_type character varying NOT NULL,
  results_count integer DEFAULT 0,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT location_search_history_pkey PRIMARY KEY (id),
  CONSTRAINT location_search_history_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.location_zip_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  location_id uuid NOT NULL,
  zip_code character varying NOT NULL,
  country character varying DEFAULT 'USA'::character varying,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT location_zip_codes_pkey PRIMARY KEY (id),
  CONSTRAINT location_zip_codes_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.locations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  business_id uuid NOT NULL,
  name character varying NOT NULL,
  address text,
  city character varying,
  state character varying,
  postal_code character varying,
  country character varying DEFAULT 'USA'::character varying,
  latitude numeric CHECK (latitude IS NULL OR latitude >= '-90'::integer::numeric AND latitude <= 90::numeric),
  longitude numeric CHECK (longitude IS NULL OR longitude >= '-180'::integer::numeric AND longitude <= 180::numeric),
  location_type character varying DEFAULT 'service_area'::character varying,
  active boolean DEFAULT true CHECK (active IS NOT NULL),
  osm_place_id character varying,
  osm_type character varying,
  osm_class character varying,
  osm_display_name text,
  service_radius_km numeric CHECK (service_radius_km IS NULL OR service_radius_km > 0::numeric),
  service_area_polygon USER-DEFINED,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT locations_pkey PRIMARY KEY (id),
  CONSTRAINT locations_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT locations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.marketing_coupons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  code text NOT NULL,
  description text,
  discount_type text NOT NULL CHECK (discount_type = ANY (ARRAY['percentage'::text, 'fixed'::text])),
  discount_value numeric NOT NULL,
  start_date date,
  end_date date,
  usage_limit integer,
  min_order numeric,
  active boolean DEFAULT true,
  facebook_coupon boolean DEFAULT false,
  allow_gift_cards boolean DEFAULT false,
  allow_referrals boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  name text,
  CONSTRAINT marketing_coupons_pkey PRIMARY KEY (id),
  CONSTRAINT marketing_coupons_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.marketing_daily_discounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  discount_type text NOT NULL CHECK (discount_type = ANY (ARRAY['percentage'::text, 'fixed'::text])),
  discount_value numeric NOT NULL,
  start_date date,
  end_date date,
  start_time time without time zone,
  end_time time without time zone,
  days ARRAY NOT NULL,
  applies_to text,
  services text,
  categories text,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT marketing_daily_discounts_pkey PRIMARY KEY (id),
  CONSTRAINT marketing_daily_discounts_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.marketing_gift_cards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  code text NOT NULL,
  amount numeric NOT NULL,
  active boolean DEFAULT true,
  expires_in_months integer DEFAULT 12,
  auto_generate_codes boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT marketing_gift_cards_pkey PRIMARY KEY (id),
  CONSTRAINT marketing_gift_cards_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text,
  phone text,
  role text DEFAULT 'provider'::text CHECK (role = ANY (ARRAY['customer'::text, 'provider'::text, 'admin'::text])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  business_id uuid,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.provider_availability (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_available boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  business_id uuid,
  CONSTRAINT provider_availability_pkey PRIMARY KEY (id),
  CONSTRAINT provider_availability_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.provider_invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  email character varying NOT NULL,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  phone character varying,
  address text,
  provider_type character varying DEFAULT 'individual'::character varying CHECK (provider_type::text = ANY (ARRAY['individual'::character varying, 'team'::character varying]::text[])),
  invitation_token character varying NOT NULL UNIQUE,
  temp_password character varying,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'expired'::character varying, 'cancelled'::character varying]::text[])),
  invited_by uuid,
  invited_at timestamp with time zone DEFAULT now(),
  accepted_at timestamp with time zone,
  expires_at timestamp with time zone DEFAULT (now() + '7 days'::interval),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT provider_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT provider_invitations_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT provider_invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id)
);
CREATE TABLE public.service_providers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  business_id uuid NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL,
  phone text,
  address text,
  specialization text DEFAULT 'General Services'::text,
  rating numeric DEFAULT 0.0,
  completed_jobs integer DEFAULT 0,
  status text DEFAULT 'active'::text,
  provider_type text DEFAULT 'individual'::text,
  send_email_notification boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_providers_pkey PRIMARY KEY (id),
  CONSTRAINT service_providers_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  base_price numeric NOT NULL,
  duration_hours integer NOT NULL,
  service_type text NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  business_id uuid,
  CONSTRAINT services_pkey PRIMARY KEY (id),
  CONSTRAINT services_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);
CREATE TABLE public.staff (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  business_id uuid NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL,
  role text NOT NULL DEFAULT 'staff'::text,
  gender text,
  phone text,
  alternate_phone text,
  address text,
  apartment text,
  send_invitation boolean NOT NULL DEFAULT true,
  image text,
  status text NOT NULL DEFAULT 'active'::text,
  last_active timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT staff_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email character varying NOT NULL UNIQUE,
  first_name character varying,
  last_name character varying,
  phone character varying,
  role character varying DEFAULT 'customer'::character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);